== Related Works

Jain et al. @jainAnalyzingComparingLakehouse2023 compare Apache Hudi, Apache Iceberg, and Delta Lake based on transaction semantics and the results of a benchmark on 3 TB of TPC-DS data on Apache Spark on AWS EMR and S3 using the default configurations of each format.

In his master's thesis, "Study and Comparison of Data Lakehouse Systems," Hellman compares the ingestion speed and query performance of Apache Hudi, Apache Iceberg, and Delta Lake on a single-node Databricks cluster for different scaling levels of data generated by an edge-based vibration monitoring system installed on the main engines of a cruise ferry traveling between Finland and Sweden @hellmanStudyComparisonData2023.

Zeng et al. evaluate the two columnar storage formats Apache Parquet and Apache ORC using a custom benchmark that can sweep data distribution to demonstrate the differences in encoding algorithms in the namesake for this thesis @zengEmpiricalEvaluationColumnar2023.

Liu et al. @liuDeepDiveCommon2023 evaluate columnar formats such as Apache Parquet, Apache ORC, and Apache Arrow for use as an internal format in a DBMS, in particular their overhead of transcoding on-disk to in-memory representations.
